name: Build cloudflared

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.3'  # 确保 Go 版本大于或等于 1.24.3
          check-latest: true       # 检查是否有最新版本
 
      - name: Get latest release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r .tag_name)
          echo "Latest release is $latest_release"
          echo "::set-output name=version::$latest_release"

      - name: Download release
        run: |
          version=${{ steps.get_release.outputs.version }}
          mkdir -p /tmp/cloudflared
          curl -L "https://github.com/cloudflare/cloudflared/archive/refs/tags/${version}.tar.gz" -o "/tmp/cloudflared/cloudflared-${version}.tar.gz"
          tar -xzf "/tmp/cloudflared/cloudflared-${version}.tar.gz" -C /tmp/cloudflared

      - name: Build cloudflared
        run: |
          cd "/tmp/cloudflared/cloudflared-${{ steps.get_release.outputs.version }}/cmd/cloudflared/"
          version=${{ steps.get_release.outputs.version }}
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -v -a -installsuffix cgo -ldflags "-s -w -extldflags '-static' -X 'main.Version=${version}' -X 'main.BuildTime=$(date +%Y-%m-%d-%H%M) UTC'" -o cloudflared .

      - name: Upload binary to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token
        run: |
          version=${{ steps.get_release.outputs.version }}
          target_path="$GITHUB_WORKSPACE/cloudflardReleases/${version}/"

          # 创建目标目录
          mkdir -p "$(dirname "$target_path")"

          # 移动二进制文件到目标目录
          mv -f "/tmp/cloudflared/cloudflared-${version}/cmd/cloudflared/cloudflared" "${target_path}"

          # 提交更改到 GitHub
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$target_path"
          git commit -m "Upload cloudflared binary for version $version"
          git push
